[2025-08-01T08:21:17.022+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/test.py
[2025-08-01T08:21:17.023+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:21:17.024+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:21:17.024+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:21:18.953+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:21:18.951+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:21:18.953+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:21:18.966+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.949 seconds
[2025-08-01T08:21:49.173+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/test.py
[2025-08-01T08:21:49.174+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:21:49.175+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:21:49.175+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:21:49.651+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:21:49.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:21:49.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:21:49.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.493 seconds
[2025-08-01T08:22:11.789+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/test.py
[2025-08-01T08:22:11.798+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:22:11.800+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:22:11.800+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:22:12.290+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:22:12.289+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:22:12.291+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:22:12.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.525 seconds
[2025-08-01T08:22:42.469+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/test.py
[2025-08-01T08:22:42.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:22:42.479+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:22:42.479+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:22:42.913+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:22:42.912+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:22:42.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:22:42.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.467 seconds
[2025-08-01T08:23:13.092+0000] {processor.py:186} INFO - Started process (PID=234) to work on /opt/airflow/dags/test.py
[2025-08-01T08:23:13.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:23:13.103+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:23:13.103+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:23:13.526+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:23:13.525+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:23:13.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:23:13.546+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.457 seconds
[2025-08-01T08:23:43.715+0000] {processor.py:186} INFO - Started process (PID=246) to work on /opt/airflow/dags/test.py
[2025-08-01T08:23:43.723+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:23:43.725+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:23:43.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:23:44.197+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:23:44.196+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:23:44.197+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:23:44.216+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.505 seconds
[2025-08-01T08:24:14.391+0000] {processor.py:186} INFO - Started process (PID=258) to work on /opt/airflow/dags/test.py
[2025-08-01T08:24:14.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:24:14.401+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:24:14.401+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:24:14.818+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:24:14.817+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:24:14.818+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:24:14.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.452 seconds
[2025-08-01T08:24:39.988+0000] {processor.py:186} INFO - Started process (PID=284) to work on /opt/airflow/dags/test.py
[2025-08-01T08:24:39.996+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:24:39.998+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:24:39.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:24:40.514+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:24:40.513+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:24:40.514+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:24:40.533+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.549 seconds
[2025-08-01T08:25:10.699+0000] {processor.py:186} INFO - Started process (PID=299) to work on /opt/airflow/dags/test.py
[2025-08-01T08:25:10.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:25:10.709+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:25:10.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:25:11.135+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:25:11.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:25:11.136+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:25:11.154+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.458 seconds
[2025-08-01T08:25:41.298+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/test.py
[2025-08-01T08:25:41.307+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:25:41.308+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:25:41.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:25:41.770+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:25:41.768+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:25:41.770+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:25:41.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.495 seconds
[2025-08-01T08:26:11.955+0000] {processor.py:186} INFO - Started process (PID=323) to work on /opt/airflow/dags/test.py
[2025-08-01T08:26:11.957+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:26:11.959+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:26:11.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:26:12.390+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:26:12.388+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:26:12.390+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:26:12.408+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.458 seconds
[2025-08-01T08:26:42.571+0000] {processor.py:186} INFO - Started process (PID=335) to work on /opt/airflow/dags/test.py
[2025-08-01T08:26:42.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:26:42.580+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:26:42.580+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:26:43.035+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:26:43.034+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:26:43.035+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:26:43.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.487 seconds
[2025-08-01T08:27:13.217+0000] {processor.py:186} INFO - Started process (PID=347) to work on /opt/airflow/dags/test.py
[2025-08-01T08:27:13.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:27:13.227+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:27:13.227+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:27:13.659+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:27:13.658+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:27:13.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:27:13.670+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.457 seconds
[2025-08-01T08:27:43.833+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/test.py
[2025-08-01T08:27:43.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:27:43.843+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:27:43.843+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:27:44.279+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:27:44.277+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:27:44.280+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:27:44.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.473 seconds
[2025-08-01T08:28:14.459+0000] {processor.py:186} INFO - Started process (PID=371) to work on /opt/airflow/dags/test.py
[2025-08-01T08:28:14.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:28:14.469+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:28:14.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:28:14.899+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:28:14.898+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:28:14.899+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:28:14.917+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.461 seconds
[2025-08-01T08:28:45.073+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/test.py
[2025-08-01T08:28:45.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:28:45.075+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:28:45.075+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:28:45.519+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:28:45.517+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:28:45.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:28:45.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.469 seconds
[2025-08-01T08:29:15.694+0000] {processor.py:186} INFO - Started process (PID=395) to work on /opt/airflow/dags/test.py
[2025-08-01T08:29:15.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:29:15.704+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:29:15.704+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:29:16.149+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:29:16.148+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:29:16.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:29:16.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.477 seconds
[2025-08-01T08:29:46.322+0000] {processor.py:186} INFO - Started process (PID=407) to work on /opt/airflow/dags/test.py
[2025-08-01T08:29:46.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:29:46.324+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:29:46.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:29:46.756+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:29:46.755+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:29:46.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:29:46.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.457 seconds
[2025-08-01T08:30:16.928+0000] {processor.py:186} INFO - Started process (PID=419) to work on /opt/airflow/dags/test.py
[2025-08-01T08:30:16.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:30:16.938+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:30:16.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:30:17.361+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:30:17.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:30:17.362+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:30:17.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.448 seconds
[2025-08-01T08:30:47.527+0000] {processor.py:186} INFO - Started process (PID=431) to work on /opt/airflow/dags/test.py
[2025-08-01T08:30:47.535+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:30:47.537+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:30:47.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:30:48.006+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:30:48.005+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 53, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:30:48.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:30:48.016+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.495 seconds
[2025-08-01T08:31:17.180+0000] {processor.py:186} INFO - Started process (PID=443) to work on /opt/airflow/dags/test.py
[2025-08-01T08:31:17.189+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:31:17.191+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:31:17.190+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:31:17.641+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:31:17.640+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 47, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:31:17.642+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:31:17.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.486 seconds
[2025-08-01T08:31:47.814+0000] {processor.py:186} INFO - Started process (PID=455) to work on /opt/airflow/dags/test.py
[2025-08-01T08:31:47.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:31:47.825+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:31:47.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:31:48.261+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:31:48.260+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 47, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:31:48.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:31:48.279+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.468 seconds
[2025-08-01T08:32:18.431+0000] {processor.py:186} INFO - Started process (PID=467) to work on /opt/airflow/dags/test.py
[2025-08-01T08:32:18.440+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:32:18.442+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:32:18.442+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:32:18.875+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:32:18.874+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 47, in <module>
    process_data_task = BashOperator(
                        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: process_data_task). Invalid arguments were:
**kwargs: {'op_args': [], 'op_kwargs': {'doc': "{{ task_instance.xcom_pull(task_ids='fetch_data_task') }}"}, 'provide_context': True}
[2025-08-01T08:32:18.875+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:32:18.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.466 seconds
[2025-08-01T08:32:39.559+0000] {processor.py:186} INFO - Started process (PID=479) to work on /opt/airflow/dags/test.py
[2025-08-01T08:32:39.567+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:32:39.569+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:32:39.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:32:40.061+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:32:40.060+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 41, in <module>
    fetch_data_task = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-08-01T08:32:40.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:32:40.072+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.518 seconds
[2025-08-01T08:33:04.119+0000] {processor.py:186} INFO - Started process (PID=485) to work on /opt/airflow/dags/test.py
[2025-08-01T08:33:04.120+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:33:04.122+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:33:04.121+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:33:04.576+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:33:04.575+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 41, in <module>
    fetch_data_task = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-08-01T08:33:04.576+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:33:04.594+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.479 seconds
[2025-08-01T08:33:34.777+0000] {processor.py:186} INFO - Started process (PID=498) to work on /opt/airflow/dags/test.py
[2025-08-01T08:33:34.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:33:34.787+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:33:34.787+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:33:35.273+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:33:35.272+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 41, in <module>
    fetch_data_task = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-08-01T08:33:35.273+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:33:35.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.511 seconds
[2025-08-01T08:33:52.402+0000] {processor.py:186} INFO - Started process (PID=510) to work on /opt/airflow/dags/test.py
[2025-08-01T08:33:52.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:33:52.403+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:33:52.403+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:33:52.849+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:33:52.848+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 41, in <module>
    fetch_data_task = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-08-01T08:33:52.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:33:52.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.469 seconds
[2025-08-01T08:34:23.037+0000] {processor.py:186} INFO - Started process (PID=522) to work on /opt/airflow/dags/test.py
[2025-08-01T08:34:23.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:34:23.047+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:34:23.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:34:23.494+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:34:23.493+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 41, in <module>
    fetch_data_task = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-08-01T08:34:23.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:34:23.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.486 seconds
[2025-08-01T08:34:28.068+0000] {processor.py:186} INFO - Started process (PID=528) to work on /opt/airflow/dags/test.py
[2025-08-01T08:34:28.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:34:28.078+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:34:28.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:34:28.522+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:34:28.520+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 41, in <module>
    fetch_data_task = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-08-01T08:34:28.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:34:28.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.475 seconds
[2025-08-01T08:34:47.666+0000] {processor.py:186} INFO - Started process (PID=540) to work on /opt/airflow/dags/test.py
[2025-08-01T08:34:47.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:34:47.675+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:34:47.675+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:34:48.118+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:34:48.117+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 41, in <module>
    fetch_data_task = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-08-01T08:34:48.119+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:34:48.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.467 seconds
[2025-08-01T08:35:04.224+0000] {processor.py:186} INFO - Started process (PID=546) to work on /opt/airflow/dags/test.py
[2025-08-01T08:35:04.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:35:04.226+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:35:04.226+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:35:04.711+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:35:04.710+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 41, in <module>
    fetch_data_task = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-08-01T08:35:04.712+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:35:04.730+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.511 seconds
[2025-08-01T08:35:32.413+0000] {processor.py:186} INFO - Started process (PID=558) to work on /opt/airflow/dags/test.py
[2025-08-01T08:35:32.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:35:32.423+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:35:32.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:35:32.869+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:35:32.868+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 41, in <module>
    fetch_data_task = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-08-01T08:35:32.870+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:35:32.888+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.479 seconds
[2025-08-01T08:36:03.050+0000] {processor.py:186} INFO - Started process (PID=570) to work on /opt/airflow/dags/test.py
[2025-08-01T08:36:03.058+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:36:03.060+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:36:03.060+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:36:03.499+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:36:03.497+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 41, in <module>
    fetch_data_task = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-08-01T08:36:03.499+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:36:03.517+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.473 seconds
[2025-08-01T08:36:33.698+0000] {processor.py:186} INFO - Started process (PID=582) to work on /opt/airflow/dags/test.py
[2025-08-01T08:36:33.699+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:36:33.701+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:36:33.700+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:36:34.192+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:36:34.191+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 41, in <module>
    fetch_data_task = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-08-01T08:36:34.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:36:34.211+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.518 seconds
[2025-08-01T08:36:57.339+0000] {processor.py:186} INFO - Started process (PID=594) to work on /opt/airflow/dags/test.py
[2025-08-01T08:36:57.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:36:57.350+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:36:57.349+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:36:57.784+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:36:57.782+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 41, in <module>
    fetch_data_task = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-08-01T08:36:57.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:36:57.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.468 seconds
[2025-08-01T08:37:28.475+0000] {processor.py:186} INFO - Started process (PID=606) to work on /opt/airflow/dags/test.py
[2025-08-01T08:37:28.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:37:28.485+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:37:28.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:37:28.965+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:37:28.964+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 41, in <module>
    fetch_data_task = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-08-01T08:37:28.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:37:28.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.508 seconds
[2025-08-01T08:37:34.553+0000] {processor.py:186} INFO - Started process (PID=612) to work on /opt/airflow/dags/test.py
[2025-08-01T08:37:34.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:37:34.558+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:37:34.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:37:35.024+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:37:35.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 41, in <module>
    fetch_data_task = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-08-01T08:37:35.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:37:35.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.487 seconds
[2025-08-01T08:38:05.317+0000] {processor.py:186} INFO - Started process (PID=625) to work on /opt/airflow/dags/test.py
[2025-08-01T08:38:05.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:38:05.320+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:38:05.319+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:38:05.660+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:38:05.659+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 41, in <module>
    fetch_data_task = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-08-01T08:38:05.661+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:38:05.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.369 seconds
[2025-08-01T08:38:27.819+0000] {processor.py:186} INFO - Started process (PID=637) to work on /opt/airflow/dags/test.py
[2025-08-01T08:38:27.820+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:38:27.821+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:38:27.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:38:28.160+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:38:28.158+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 43, in <module>
    python_callable= get_data
                     ^^^^^^^^
NameError: name 'get_data' is not defined. Did you mean: 'fetch_data'?
[2025-08-01T08:38:28.162+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:38:28.182+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.367 seconds
[2025-08-01T08:38:39.876+0000] {processor.py:186} INFO - Started process (PID=643) to work on /opt/airflow/dags/test.py
[2025-08-01T08:38:39.885+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:38:39.887+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:38:39.886+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:38:40.223+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:38:40.221+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 43, in <module>
    python_callable= get_data
                     ^^^^^^^^
NameError: name 'get_data' is not defined. Did you mean: 'fetch_data'?
[2025-08-01T08:38:40.224+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:38:40.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.365 seconds
[2025-08-01T08:38:53.335+0000] {processor.py:186} INFO - Started process (PID=655) to work on /opt/airflow/dags/test.py
[2025-08-01T08:38:53.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:38:53.345+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:38:53.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:38:53.678+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:38:53.677+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 43, in <module>
    python_callable= get_data
                     ^^^^^^^^
NameError: name 'get_data' is not defined. Did you mean: 'fetch_data'?
[2025-08-01T08:38:53.679+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:38:53.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.370 seconds
[2025-08-01T08:38:59.746+0000] {processor.py:186} INFO - Started process (PID=661) to work on /opt/airflow/dags/test.py
[2025-08-01T08:38:59.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:38:59.751+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:38:59.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:38:59.754+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:38:59.753+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 15
    from  Transform import 
                           ^
SyntaxError: invalid syntax
[2025-08-01T08:38:59.754+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:38:59.766+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.026 seconds
[2025-08-01T08:39:06.793+0000] {processor.py:186} INFO - Started process (PID=666) to work on /opt/airflow/dags/test.py
[2025-08-01T08:39:06.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:39:06.795+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:39:06.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:39:07.124+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:39:07.122+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 43, in <module>
    python_callable= get_data
                     ^^^^^^^^
NameError: name 'get_data' is not defined. Did you mean: 'fetch_data'?
[2025-08-01T08:39:07.125+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:39:07.144+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.356 seconds
[2025-08-01T08:39:36.315+0000] {processor.py:186} INFO - Started process (PID=678) to work on /opt/airflow/dags/test.py
[2025-08-01T08:39:36.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:39:36.325+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:39:36.325+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:39:36.640+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:39:36.638+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 62, in <module>
    python_callable=Create_table,
                    ^^^^^^^^^^^^
NameError: name 'Create_table' is not defined. Did you mean: 'create_table'?
[2025-08-01T08:39:36.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:39:36.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.350 seconds
[2025-08-01T08:39:56.782+0000] {processor.py:186} INFO - Started process (PID=690) to work on /opt/airflow/dags/test.py
[2025-08-01T08:39:56.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:39:56.792+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:39:56.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:39:57.114+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:39:57.112+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 73, in <module>
    python_callable= Check_table
                     ^^^^^^^^^^^
NameError: name 'Check_table' is not defined. Did you mean: 'check_table'?
[2025-08-01T08:39:57.115+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:39:57.126+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.348 seconds
[2025-08-01T08:40:22.264+0000] {processor.py:186} INFO - Started process (PID=702) to work on /opt/airflow/dags/test.py
[2025-08-01T08:40:22.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:40:22.276+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:40:22.275+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:40:22.606+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:40:22.814+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:40:22.814+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:test
[2025-08-01T08:40:22.820+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:40:22.820+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:test
[2025-08-01T08:40:22.824+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:40:22.824+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:test
[2025-08-01T08:40:22.828+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:40:22.828+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:test
[2025-08-01T08:40:22.831+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:40:22.831+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:test
[2025-08-01T08:40:22.835+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:40:22.835+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:test
[2025-08-01T08:40:22.838+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:40:22.838+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:test
[2025-08-01T08:40:22.838+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:40:22.838+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T08:40:22.846+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:40:22.845+0000] {dag.py:3262} INFO - Creating ORM DAG for test
[2025-08-01T08:40:22.852+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:40:22.852+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T08:40:22.861+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.602 seconds
[2025-08-01T08:40:53.449+0000] {processor.py:186} INFO - Started process (PID=718) to work on /opt/airflow/dags/test.py
[2025-08-01T08:40:53.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:40:53.460+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:40:53.460+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:40:53.792+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:40:53.810+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:40:53.809+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T08:40:53.825+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:40:53.825+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-08-01 00:00:00+00:00, run_after=2025-08-02 00:00:00+00:00
[2025-08-01T08:40:53.979+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.535 seconds
[2025-08-01T08:41:24.145+0000] {processor.py:186} INFO - Started process (PID=730) to work on /opt/airflow/dags/test.py
[2025-08-01T08:41:24.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:41:24.155+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:41:24.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:41:24.488+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:41:24.507+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:41:24.506+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T08:41:24.522+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:41:24.522+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-08-01 00:00:00+00:00, run_after=2025-08-02 00:00:00+00:00
[2025-08-01T08:41:24.541+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.400 seconds
[2025-08-01T08:41:37.586+0000] {processor.py:186} INFO - Started process (PID=736) to work on /opt/airflow/dags/test.py
[2025-08-01T08:41:37.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:41:37.596+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:41:37.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:41:37.910+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:41:37.927+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:41:37.927+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T08:41:37.942+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:41:37.941+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-08-01 00:00:00+00:00, run_after=2025-08-02 00:00:00+00:00
[2025-08-01T08:41:37.960+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.379 seconds
[2025-08-01T08:42:04.093+0000] {processor.py:186} INFO - Started process (PID=752) to work on /opt/airflow/dags/test.py
[2025-08-01T08:42:04.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:42:04.105+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:42:04.105+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:42:04.443+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:42:04.462+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:42:04.461+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T08:42:04.481+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:42:04.481+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-08-01 00:00:00+00:00, run_after=2025-08-02 00:00:00+00:00
[2025-08-01T08:42:04.502+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.414 seconds
[2025-08-01T08:42:34.668+0000] {processor.py:186} INFO - Started process (PID=768) to work on /opt/airflow/dags/test.py
[2025-08-01T08:42:34.668+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:42:34.670+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:42:34.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:42:35.022+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:42:35.039+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:42:35.039+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T08:42:35.054+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:42:35.053+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-08-01 00:00:00+00:00, run_after=2025-08-02 00:00:00+00:00
[2025-08-01T08:42:35.071+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.409 seconds
[2025-08-01T08:43:05.226+0000] {processor.py:186} INFO - Started process (PID=870) to work on /opt/airflow/dags/test.py
[2025-08-01T08:43:05.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T08:43:05.236+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:43:05.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T08:43:05.608+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T08:43:05.626+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:43:05.626+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T08:43:05.643+0000] {logging_mixin.py:190} INFO - [2025-08-01T08:43:05.643+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-08-01 00:00:00+00:00, run_after=2025-08-02 00:00:00+00:00
[2025-08-01T08:43:05.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.573 seconds
[2025-08-01T11:35:46.196+0000] {processor.py:186} INFO - Started process (PID=190) to work on /opt/airflow/dags/test.py
[2025-08-01T11:35:46.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:35:46.199+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:35:46.198+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:35:46.891+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:35:46.890+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 13, in <module>
    from  kafka_producer import send_df_to_kafka
ImportError: cannot import name 'send_df_to_kafka' from 'kafka_producer' (/opt/airflow/scripts/kafka_producer.py). Did you mean: 'send_dataframe_to_kafka'?
[2025-08-01T11:35:46.892+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:35:46.906+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.720 seconds
[2025-08-01T11:36:17.149+0000] {processor.py:186} INFO - Started process (PID=242) to work on /opt/airflow/dags/test.py
[2025-08-01T11:36:17.151+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:36:17.154+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:36:17.153+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:36:18.143+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:36:18.141+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 13, in <module>
    from  kafka_producer import send_df_to_kafka
ImportError: cannot import name 'send_df_to_kafka' from 'kafka_producer' (/opt/airflow/scripts/kafka_producer.py). Did you mean: 'send_dataframe_to_kafka'?
[2025-08-01T11:36:18.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:36:18.172+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.031 seconds
[2025-08-01T11:37:24.430+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/test.py
[2025-08-01T11:37:24.430+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:37:24.432+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:37:24.432+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:37:25.864+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:37:25.863+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 13, in <module>
    from  kafka_producer import send_df_to_kafka
ImportError: cannot import name 'send_df_to_kafka' from 'kafka_producer' (/opt/airflow/scripts/kafka_producer.py). Did you mean: 'send_dataframe_to_kafka'?
[2025-08-01T11:37:25.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:37:25.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.452 seconds
[2025-08-01T11:37:56.088+0000] {processor.py:186} INFO - Started process (PID=199) to work on /opt/airflow/dags/test.py
[2025-08-01T11:37:56.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:37:56.101+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:37:56.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:37:57.146+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:37:57.145+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 13, in <module>
    from  kafka_producer import send_df_to_kafka
ImportError: cannot import name 'send_df_to_kafka' from 'kafka_producer' (/opt/airflow/scripts/kafka_producer.py). Did you mean: 'send_dataframe_to_kafka'?
[2025-08-01T11:37:57.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:37:57.177+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.100 seconds
[2025-08-01T11:38:27.428+0000] {processor.py:186} INFO - Started process (PID=211) to work on /opt/airflow/dags/test.py
[2025-08-01T11:38:27.437+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:38:27.441+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:38:27.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:38:28.433+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:38:28.431+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 15, in <module>
    from  Transform import transform_data
ImportError: cannot import name 'transform_data' from 'Transform' (/opt/airflow/scripts/Transform.py)
[2025-08-01T11:38:28.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:38:28.454+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.033 seconds
[2025-08-01T11:38:58.707+0000] {processor.py:186} INFO - Started process (PID=223) to work on /opt/airflow/dags/test.py
[2025-08-01T11:38:58.716+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:38:58.720+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:38:58.720+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:38:59.746+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:38:59.743+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 15, in <module>
    from  Transform import transform_data
ImportError: cannot import name 'transform_data' from 'Transform' (/opt/airflow/scripts/Transform.py)
[2025-08-01T11:38:59.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:38:59.771+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.072 seconds
[2025-08-01T11:39:30.043+0000] {processor.py:186} INFO - Started process (PID=235) to work on /opt/airflow/dags/test.py
[2025-08-01T11:39:30.053+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:39:30.057+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:39:30.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:39:31.049+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:39:31.203+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:39:31.202+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:test
[2025-08-01T11:39:31.216+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:39:31.215+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:test
[2025-08-01T11:39:31.224+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:39:31.224+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:test
[2025-08-01T11:39:31.234+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:39:31.233+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:test
[2025-08-01T11:39:31.242+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:39:31.241+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:test
[2025-08-01T11:39:31.251+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:39:31.250+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:test
[2025-08-01T11:39:31.259+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:39:31.259+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:test
[2025-08-01T11:39:31.260+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:39:31.260+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:39:31.277+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:39:31.277+0000] {dag.py:3262} INFO - Creating ORM DAG for test
[2025-08-01T11:39:31.290+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:39:31.290+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T11:39:31.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.276 seconds
[2025-08-01T11:40:01.374+0000] {processor.py:186} INFO - Started process (PID=247) to work on /opt/airflow/dags/test.py
[2025-08-01T11:40:01.383+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:40:01.386+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:40:01.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:40:02.289+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:40:02.319+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:40:02.319+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:40:02.346+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:40:02.346+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T11:40:02.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.000 seconds
[2025-08-01T11:40:32.592+0000] {processor.py:186} INFO - Started process (PID=259) to work on /opt/airflow/dags/test.py
[2025-08-01T11:40:32.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:40:32.597+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:40:32.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:40:33.593+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:40:33.631+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:40:33.630+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:40:33.664+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:40:33.664+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-08-01 00:00:00+00:00, run_after=2025-08-02 00:00:00+00:00
[2025-08-01T11:40:33.690+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.106 seconds
[2025-08-01T11:41:03.945+0000] {processor.py:186} INFO - Started process (PID=360) to work on /opt/airflow/dags/test.py
[2025-08-01T11:41:03.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:41:03.958+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:41:03.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:41:04.950+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:41:04.983+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:41:04.983+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:41:05.013+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:41:05.013+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-08-01 00:00:00+00:00, run_after=2025-08-02 00:00:00+00:00
[2025-08-01T11:41:05.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.098 seconds
[2025-08-01T11:41:35.294+0000] {processor.py:186} INFO - Started process (PID=372) to work on /opt/airflow/dags/test.py
[2025-08-01T11:41:35.296+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:41:35.299+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:41:35.298+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:41:36.218+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:41:36.252+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:41:36.251+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:41:36.286+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:41:36.286+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-08-01 00:00:00+00:00, run_after=2025-08-02 00:00:00+00:00
[2025-08-01T11:41:36.307+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.024 seconds
[2025-08-01T11:42:06.565+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/test.py
[2025-08-01T11:42:06.574+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:42:06.578+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:42:06.577+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:42:07.609+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:42:07.645+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:42:07.644+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:42:07.673+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:42:07.673+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-08-01 00:00:00+00:00, run_after=2025-08-02 00:00:00+00:00
[2025-08-01T11:42:07.693+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.139 seconds
[2025-08-01T11:42:37.924+0000] {processor.py:186} INFO - Started process (PID=396) to work on /opt/airflow/dags/test.py
[2025-08-01T11:42:37.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:42:37.937+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:42:37.937+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:42:38.933+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:42:38.968+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:42:38.968+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:42:38.999+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:42:38.998+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-08-01 00:00:00+00:00, run_after=2025-08-02 00:00:00+00:00
[2025-08-01T11:42:39.031+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.114 seconds
[2025-08-01T11:54:56.474+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/test.py
[2025-08-01T11:54:56.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:54:56.477+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:54:56.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:54:57.883+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:54:57.978+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:54:57.977+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:test
[2025-08-01T11:54:57.986+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:54:57.986+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:test
[2025-08-01T11:54:57.991+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:54:57.991+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:test
[2025-08-01T11:54:57.997+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:54:57.997+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:test
[2025-08-01T11:54:58.002+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:54:58.002+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:test
[2025-08-01T11:54:58.007+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:54:58.007+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:test
[2025-08-01T11:54:58.013+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:54:58.012+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:test
[2025-08-01T11:54:58.013+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:54:58.013+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:54:58.025+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:54:58.025+0000] {dag.py:3262} INFO - Creating ORM DAG for test
[2025-08-01T11:54:58.033+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:54:58.033+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T11:54:58.046+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.577 seconds
[2025-08-01T11:55:28.273+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/test.py
[2025-08-01T11:55:28.282+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:55:28.286+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:55:28.285+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:55:29.213+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:55:29.243+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:55:29.242+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:55:29.269+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:55:29.268+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T11:55:29.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.026 seconds
[2025-08-01T11:55:59.555+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/test.py
[2025-08-01T11:55:59.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:55:59.559+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:55:59.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:56:00.494+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:56:00.529+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:56:00.528+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:56:00.557+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:56:00.557+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T11:56:00.582+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.035 seconds
[2025-08-01T11:56:30.812+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/test.py
[2025-08-01T11:56:30.821+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:56:30.824+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:56:30.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:56:31.807+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:56:31.839+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:56:31.838+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:56:31.866+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:56:31.866+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T11:56:31.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.082 seconds
[2025-08-01T11:57:02.101+0000] {processor.py:186} INFO - Started process (PID=234) to work on /opt/airflow/dags/test.py
[2025-08-01T11:57:02.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:57:02.113+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:57:02.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:57:02.957+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:57:02.988+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:57:02.987+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:57:03.014+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:57:03.013+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T11:57:03.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.940 seconds
[2025-08-01T11:57:33.273+0000] {processor.py:186} INFO - Started process (PID=246) to work on /opt/airflow/dags/test.py
[2025-08-01T11:57:33.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:57:33.284+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:57:33.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:57:34.188+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:57:34.222+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:57:34.222+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:57:34.253+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:57:34.253+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T11:57:34.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.011 seconds
[2025-08-01T11:58:38.406+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/test.py
[2025-08-01T11:58:38.406+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:58:38.408+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:58:38.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:58:39.668+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:58:39.771+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:58:39.771+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:test
[2025-08-01T11:58:39.780+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:58:39.780+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:test
[2025-08-01T11:58:39.786+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:58:39.785+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:test
[2025-08-01T11:58:39.792+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:58:39.791+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:test
[2025-08-01T11:58:39.797+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:58:39.797+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:test
[2025-08-01T11:58:39.803+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:58:39.803+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:test
[2025-08-01T11:58:39.808+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:58:39.807+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:test
[2025-08-01T11:58:39.808+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:58:39.808+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:58:39.819+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:58:39.818+0000] {dag.py:3262} INFO - Creating ORM DAG for test
[2025-08-01T11:58:39.830+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:58:39.830+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T11:58:39.845+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.443 seconds
[2025-08-01T11:59:10.068+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/test.py
[2025-08-01T11:59:10.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:59:10.080+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:59:10.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:59:10.986+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:59:11.019+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:59:11.019+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:59:11.048+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:59:11.047+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T11:59:11.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.014 seconds
[2025-08-01T11:59:41.329+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/test.py
[2025-08-01T11:59:41.338+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T11:59:41.341+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:59:41.341+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T11:59:42.363+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T11:59:42.401+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:59:42.400+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T11:59:42.431+0000] {logging_mixin.py:190} INFO - [2025-08-01T11:59:42.431+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T11:59:42.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.145 seconds
[2025-08-01T12:00:12.731+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/test.py
[2025-08-01T12:00:12.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T12:00:12.743+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:00:12.742+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T12:00:13.588+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T12:00:13.619+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:00:13.618+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T12:00:13.647+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:00:13.646+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T12:00:13.666+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.942 seconds
[2025-08-01T12:00:43.899+0000] {processor.py:186} INFO - Started process (PID=234) to work on /opt/airflow/dags/test.py
[2025-08-01T12:00:43.900+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T12:00:43.903+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:00:43.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T12:00:44.805+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T12:00:44.838+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:00:44.837+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T12:00:44.864+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:00:44.864+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T12:00:44.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.000 seconds
[2025-08-01T12:01:15.136+0000] {processor.py:186} INFO - Started process (PID=246) to work on /opt/airflow/dags/test.py
[2025-08-01T12:01:15.145+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T12:01:15.148+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:01:15.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T12:01:16.048+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T12:01:16.081+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:01:16.080+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T12:01:16.109+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:01:16.108+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T12:01:16.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.002 seconds
[2025-08-01T12:01:46.372+0000] {processor.py:186} INFO - Started process (PID=258) to work on /opt/airflow/dags/test.py
[2025-08-01T12:01:46.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T12:01:46.384+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:01:46.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T12:01:47.313+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T12:01:47.347+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:01:47.346+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T12:01:47.377+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:01:47.376+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T12:01:47.410+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.047 seconds
[2025-08-01T12:02:17.599+0000] {processor.py:186} INFO - Started process (PID=270) to work on /opt/airflow/dags/test.py
[2025-08-01T12:02:17.608+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T12:02:17.610+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:02:17.610+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T12:02:18.519+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T12:02:18.554+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:02:18.552+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T12:02:18.581+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:02:18.581+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T12:02:18.604+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.015 seconds
[2025-08-01T12:02:48.832+0000] {processor.py:186} INFO - Started process (PID=282) to work on /opt/airflow/dags/test.py
[2025-08-01T12:02:48.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T12:02:48.837+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:02:48.836+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T12:02:49.651+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T12:02:49.699+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:02:49.698+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T12:02:49.730+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:02:49.730+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T12:02:49.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.936 seconds
[2025-08-01T12:03:20.010+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/dags/test.py
[2025-08-01T12:03:20.019+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-08-01T12:03:20.023+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:03:20.023+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-08-01T12:03:20.739+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-08-01T12:03:20.774+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:03:20.773+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-08-01T12:03:20.805+0000] {logging_mixin.py:190} INFO - [2025-08-01T12:03:20.804+0000] {dag.py:4180} INFO - Setting next_dagrun for test to 2025-07-31 00:00:00+00:00, run_after=2025-08-01 00:00:00+00:00
[2025-08-01T12:03:20.836+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.834 seconds
