[2025-04-14T15:03:42.892+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: HemaDag.create_table scheduled__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-14T15:03:42.904+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: HemaDag.create_table scheduled__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-14T15:03:42.904+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-14T15:03:42.905+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-04-14T15:03:42.905+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-14T15:03:42.922+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_table> on 2025-04-06 00:00:00+00:00
[2025-04-14T15:03:42.932+0000] {standard_task_runner.py:55} INFO - Started process 249 to run task
[2025-04-14T15:03:42.937+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'HemaDag', 'create_table', 'scheduled__2025-04-06T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/day.py', '--cfg-path', '/tmp/tmp2d_jo0yo']
[2025-04-14T15:03:42.939+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask create_table
[2025-04-14T15:03:43.024+0000] {task_command.py:388} INFO - Running <TaskInstance: HemaDag.create_table scheduled__2025-04-06T00:00:00+00:00 [running]> on host 0c4d66587ca1
[2025-04-14T15:03:43.068+0000] {abstractoperator.py:613} ERROR - Exception rendering Jinja template for task 'create_table', field 'sql'. Template: '/opt/***/scripts/create_table.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/scripts/create_table.sql
[2025-04-14T15:03:43.070+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1493, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2115, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/scripts/create_table.sql
[2025-04-14T15:03:43.084+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=HemaDag, task_id=create_table, execution_date=20250406T000000, start_date=20250414T150342, end_date=20250414T150343
[2025-04-14T15:03:43.101+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task create_table (/opt/airflow/scripts/create_table.sql; 249)
[2025-04-14T15:03:43.148+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-14T15:03:43.176+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
