[2025-04-04T05:29:22.369+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: HemaDag.fetch_data __airflow_temporary_run_2025-04-04T05:29:21.361120+00:00__ [queued]>
[2025-04-04T05:29:22.376+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: HemaDag.fetch_data __airflow_temporary_run_2025-04-04T05:29:21.361120+00:00__ [queued]>
[2025-04-04T05:29:22.376+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T05:29:22.376+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-04-04T05:29:22.376+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T05:29:22.393+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): fetch_data> on 2025-04-04 00:00:00+00:00
[2025-04-04T05:29:22.399+0000] {standard_task_runner.py:55} INFO - Started process 462 to run task
[2025-04-04T05:29:22.402+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'HemaDag', 'fetch_data', '__***_temporary_run_2025-04-04T05:29:21.361120+00:00__', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/day.py', '--cfg-path', '/tmp/tmpcxyzmzdg']
[2025-04-04T05:29:22.403+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask fetch_data
[2025-04-04T05:29:22.450+0000] {task_command.py:388} INFO - Running <TaskInstance: HemaDag.fetch_data __airflow_temporary_run_2025-04-04T05:29:21.361120+00:00__ [running]> on host 02c55f5ad405
[2025-04-04T05:29:22.507+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HemaDag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2025-04-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=__***_temporary_run_2025-04-04T05:29:21.361120+00:00__
[2025-04-04T05:29:22.507+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-04-04T05:29:22.508+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/scripts/Extract.py']
[2025-04-04T05:29:22.522+0000] {subprocess.py:86} INFO - Output:
[2025-04-04T05:29:23.442+0000] {subprocess.py:93} INFO - Table 1 saved to: data/table_1.csv
[2025-04-04T05:29:23.443+0000] {subprocess.py:93} INFO - 
[2025-04-04T05:29:23.443+0000] {subprocess.py:93} INFO - All 1 tables saved to 'data'!
[2025-04-04T05:29:23.501+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-04T05:29:23.509+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 211, in set
    raise ValueError(f"DAG run not found on DAG {dag_id!r} with ID {run_id!r}")
ValueError: DAG run not found on DAG 'HemaDag' with ID '__***_temporary_run_2025-04-04T05:29:21.361120+00:00__'
[2025-04-04T05:29:23.515+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=HemaDag, task_id=fetch_data, execution_date=20250404T000000, start_date=20250404T052922, end_date=20250404T052923
[2025-04-04T05:29:23.523+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6 for task fetch_data ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(HemaDag, fetch_data, __airflow_temporary_run_2025-04-04T05:29:21.361120+00:00__, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'fetch_data', 'dag_id': 'HemaDag', 'run_id': '__airflow_temporary_run_2025-04-04T05:29:21.361120+00:00__', 'map_index': -1, 'start_date': datetime.datetime(2025, 4, 4, 5, 29, 22, 370818, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 4, 4, 5, 29, 23, 514617, tzinfo=Timezone('UTC')), 'duration': 1}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 462)
[2025-04-04T05:29:23.535+0000] {local_task_job.py:208} INFO - Task exited with return code 1
