[2025-04-15T06:56:55.985+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: HemaDag.send_dataframe_to_kafka_task manual__2025-04-15T06:56:48.083080+00:00 [queued]>
[2025-04-15T06:56:55.999+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: HemaDag.send_dataframe_to_kafka_task manual__2025-04-15T06:56:48.083080+00:00 [queued]>
[2025-04-15T06:56:55.999+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-15T06:56:55.999+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-04-15T06:56:55.999+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-15T06:56:56.018+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): send_dataframe_to_kafka_task> on 2025-04-15 06:56:48.083080+00:00
[2025-04-15T06:56:56.032+0000] {standard_task_runner.py:55} INFO - Started process 249 to run task
[2025-04-15T06:56:56.036+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'HemaDag', 'send_dataframe_to_kafka_task', 'manual__2025-04-15T06:56:48.083080+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/day.py', '--cfg-path', '/tmp/tmpjbpljilr']
[2025-04-15T06:56:56.039+0000] {standard_task_runner.py:83} INFO - Job 49: Subtask send_dataframe_to_kafka_task
[2025-04-15T06:56:56.132+0000] {task_command.py:388} INFO - Running <TaskInstance: HemaDag.send_dataframe_to_kafka_task manual__2025-04-15T06:56:48.083080+00:00 [running]> on host 0c4d66587ca1
[2025-04-15T06:56:56.238+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HemaDag
AIRFLOW_CTX_TASK_ID=send_dataframe_to_kafka_task
AIRFLOW_CTX_EXECUTION_DATE=2025-04-15T06:56:48.083080+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-15T06:56:48.083080+00:00
[2025-04-15T06:56:56.242+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-15T06:56:56.242+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-04-15T06:56:56.242+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-04-15T06:56:56.243+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-15T06:56:56.243+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-04-15T06:56:56.243+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-04-15T06:56:56.244+0000] {client_async.py:1048} WARNING - No node available during check_version; sleeping 0.05 secs
[2025-04-15T06:56:56.299+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-15T06:56:56.299+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-04-15T06:56:56.300+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-04-15T06:56:56.300+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-15T06:56:56.300+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-04-15T06:56:56.300+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-04-15T06:56:56.301+0000] {client_async.py:1048} WARNING - No node available during check_version; sleeping 0.09 secs
[2025-04-15T06:56:56.387+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-15T06:56:56.388+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-04-15T06:56:56.388+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-04-15T06:56:56.389+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-15T06:56:56.389+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-04-15T06:56:56.390+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-04-15T06:56:56.390+0000] {client_async.py:1048} WARNING - No node available during check_version; sleeping 0.18 secs
[2025-04-15T06:56:56.567+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-15T06:56:56.567+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-04-15T06:56:56.568+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-04-15T06:56:56.568+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-15T06:56:56.569+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-04-15T06:56:56.569+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-04-15T06:56:56.569+0000] {client_async.py:1048} WARNING - No node available during check_version; sleeping 0.38 secs
[2025-04-15T06:56:56.947+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-15T06:56:56.948+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-04-15T06:56:56.948+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-04-15T06:56:56.948+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-15T06:56:56.949+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-04-15T06:56:56.949+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-04-15T06:56:56.949+0000] {client_async.py:1048} WARNING - No node available during check_version; sleeping 0.76 secs
[2025-04-15T06:56:57.710+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-15T06:56:57.710+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-04-15T06:56:57.711+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-04-15T06:56:57.711+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-15T06:56:57.711+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-04-15T06:56:57.712+0000] {conn.py:936} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-04-15T06:56:57.712+0000] {client_async.py:1048} WARNING - No node available during check_version; sleeping 0.53 secs
[2025-04-15T06:56:58.242+0000] {logging_mixin.py:137} INFO - Error sending records to Kafka: NoBrokersAvailable
[2025-04-15T06:56:58.243+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/day.py", line 22, in send_df_to_kafka
    value_serializer=lambda x: json.dumps(x, default=str).encode('utf-8')
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 411, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 1073, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-04-15T06:56:58.259+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=HemaDag, task_id=send_dataframe_to_kafka_task, execution_date=20250415T065648, start_date=20250415T065655, end_date=20250415T065658
[2025-04-15T06:56:58.275+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 49 for task send_dataframe_to_kafka_task (NoBrokersAvailable; 249)
[2025-04-15T06:56:58.302+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-15T06:56:58.340+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
