[2025-04-14T15:21:04.043+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: HemaDag.send_to_kafka manual__2025-04-14T15:21:02.840864+00:00 [queued]>
[2025-04-14T15:21:04.059+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: HemaDag.send_to_kafka manual__2025-04-14T15:21:02.840864+00:00 [queued]>
[2025-04-14T15:21:04.059+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-14T15:21:04.059+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-04-14T15:21:04.059+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-14T15:21:04.079+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): send_to_kafka> on 2025-04-14 15:21:02.840864+00:00
[2025-04-14T15:21:04.091+0000] {standard_task_runner.py:55} INFO - Started process 681 to run task
[2025-04-14T15:21:04.095+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'HemaDag', 'send_to_kafka', 'manual__2025-04-14T15:21:02.840864+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/day.py', '--cfg-path', '/tmp/tmph_31vx9_']
[2025-04-14T15:21:04.097+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask send_to_kafka
[2025-04-14T15:21:04.193+0000] {task_command.py:388} INFO - Running <TaskInstance: HemaDag.send_to_kafka manual__2025-04-14T15:21:02.840864+00:00 [running]> on host 0c4d66587ca1
[2025-04-14T15:21:04.304+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HemaDag
AIRFLOW_CTX_TASK_ID=send_to_kafka
AIRFLOW_CTX_EXECUTION_DATE=2025-04-14T15:21:02.840864+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-14T15:21:02.840864+00:00
[2025-04-14T15:21:04.306+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-04-14T15:21:04.307+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/scripts/kafka.py']
[2025-04-14T15:21:04.328+0000] {subprocess.py:86} INFO - Output:
[2025-04-14T15:21:04.482+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-14T15:21:04.483+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/kafka.py", line 1, in <module>
[2025-04-14T15:21:04.483+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer, KafkaConsumer
[2025-04-14T15:21:04.483+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/kafka.py", line 1, in <module>
[2025-04-14T15:21:04.483+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer, KafkaConsumer
[2025-04-14T15:21:04.483+0000] {subprocess.py:93} INFO - ImportError: cannot import name 'KafkaProducer' from 'kafka' (/opt/***/scripts/kafka.py)
[2025-04-14T15:21:04.488+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-14T15:21:04.506+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-14T15:21:04.511+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=HemaDag, task_id=send_to_kafka, execution_date=20250414T152102, start_date=20250414T152104, end_date=20250414T152104
[2025-04-14T15:21:04.537+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 17 for task send_to_kafka (Bash command failed. The command returned a non-zero exit code 1.; 681)
[2025-04-14T15:21:04.587+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-14T15:21:04.614+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
