[2025-04-15T07:11:25.025+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Anas.send_dataframe_to_kafka_task manual__2025-04-15T07:11:17.948330+00:00 [queued]>
[2025-04-15T07:11:25.039+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Anas.send_dataframe_to_kafka_task manual__2025-04-15T07:11:17.948330+00:00 [queued]>
[2025-04-15T07:11:25.040+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-15T07:11:25.040+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-04-15T07:11:25.040+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-15T07:11:25.061+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): send_dataframe_to_kafka_task> on 2025-04-15 07:11:17.948330+00:00
[2025-04-15T07:11:25.074+0000] {standard_task_runner.py:55} INFO - Started process 480 to run task
[2025-04-15T07:11:25.079+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Anas', 'send_dataframe_to_kafka_task', 'manual__2025-04-15T07:11:17.948330+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/day.py', '--cfg-path', '/tmp/tmpc6gana55']
[2025-04-15T07:11:25.081+0000] {standard_task_runner.py:83} INFO - Job 64: Subtask send_dataframe_to_kafka_task
[2025-04-15T07:11:25.170+0000] {task_command.py:388} INFO - Running <TaskInstance: Anas.send_dataframe_to_kafka_task manual__2025-04-15T07:11:17.948330+00:00 [running]> on host 0c4d66587ca1
[2025-04-15T07:11:25.274+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Anas
AIRFLOW_CTX_TASK_ID=send_dataframe_to_kafka_task
AIRFLOW_CTX_EXECUTION_DATE=2025-04-15T07:11:17.948330+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-15T07:11:17.948330+00:00
[2025-04-15T07:11:25.277+0000] {logging_mixin.py:137} INFO - Error sending records to Kafka: invalid literal for int() with base 10: 'kafka'
[2025-04-15T07:11:25.278+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/day.py", line 23, in send_df_to_kafka
    value_serializer=lambda x: json.dumps(x).encode('utf-8')  )
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 411, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 1052, in check_version
    if not self._init_connect(try_node):
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 443, in _init_connect
    host, port, afi = get_ip_port_afi(broker.host)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/conn.py", line 1483, in get_ip_port_afi
    port = int(port)
ValueError: invalid literal for int() with base 10: 'kafka'
[2025-04-15T07:11:25.292+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Anas, task_id=send_dataframe_to_kafka_task, execution_date=20250415T071117, start_date=20250415T071125, end_date=20250415T071125
[2025-04-15T07:11:25.308+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 64 for task send_dataframe_to_kafka_task (invalid literal for int() with base 10: 'kafka'; 480)
[2025-04-15T07:11:25.330+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-15T07:11:25.369+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
