[2025-04-15T07:21:48.824+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Anas.send_dataframe_to_kafka_task manual__2025-04-15T07:21:42.425516+00:00 [queued]>
[2025-04-15T07:21:48.836+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Anas.send_dataframe_to_kafka_task manual__2025-04-15T07:21:42.425516+00:00 [queued]>
[2025-04-15T07:21:48.837+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-15T07:21:48.837+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-04-15T07:21:48.837+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-15T07:21:48.855+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): send_dataframe_to_kafka_task> on 2025-04-15 07:21:42.425516+00:00
[2025-04-15T07:21:48.867+0000] {standard_task_runner.py:55} INFO - Started process 289 to run task
[2025-04-15T07:21:48.872+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Anas', 'send_dataframe_to_kafka_task', 'manual__2025-04-15T07:21:42.425516+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/day.py', '--cfg-path', '/tmp/tmpe3hu_bsy']
[2025-04-15T07:21:48.874+0000] {standard_task_runner.py:83} INFO - Job 74: Subtask send_dataframe_to_kafka_task
[2025-04-15T07:21:48.954+0000] {task_command.py:388} INFO - Running <TaskInstance: Anas.send_dataframe_to_kafka_task manual__2025-04-15T07:21:42.425516+00:00 [running]> on host 0c4d66587ca1
[2025-04-15T07:21:49.047+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Anas
AIRFLOW_CTX_TASK_ID=send_dataframe_to_kafka_task
AIRFLOW_CTX_EXECUTION_DATE=2025-04-15T07:21:42.425516+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-15T07:21:42.425516+00:00
[2025-04-15T07:21:49.051+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.20.0.6', 9092)]>: connecting to kafka:9092 [('172.20.0.6', 9092) IPv4]
[2025-04-15T07:21:49.056+0000] {conn.py:615} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.20.0.6', 9092)]>: Broker version identified as 2.6
[2025-04-15T07:21:49.056+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.20.0.6', 9092)]>: Connection complete.
[2025-04-15T07:21:49.162+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.20.0.6', 9092)]>: connecting to kafka:9092 [('172.20.0.6', 9092) IPv4]
[2025-04-15T07:21:49.163+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.20.0.6', 9092)]>: Connection complete.
[2025-04-15T07:21:49.164+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.20.0.6', 9092)]>: Closing connection. 
[2025-04-15T07:21:49.171+0000] {logging_mixin.py:137} INFO - Success!
[2025-04-15T07:21:49.187+0000] {logging_mixin.py:137} INFO - Error sending records to Kafka: DataFrame is None. Check the data source or task input.
[2025-04-15T07:21:49.187+0000] {kafka.py:511} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2025-04-15T07:21:49.188+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.20.0.6', 9092)]>: Closing connection. 
[2025-04-15T07:21:49.189+0000] {logging_mixin.py:137} INFO - Kafka producer closed.
[2025-04-15T07:21:49.189+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/day.py", line 29, in send_df_to_kafka
    raise ValueError("DataFrame is None. Check the data source or task input.")
ValueError: DataFrame is None. Check the data source or task input.
[2025-04-15T07:21:49.201+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Anas, task_id=send_dataframe_to_kafka_task, execution_date=20250415T072142, start_date=20250415T072148, end_date=20250415T072149
[2025-04-15T07:21:49.223+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 74 for task send_dataframe_to_kafka_task (DataFrame is None. Check the data source or task input.; 289)
[2025-04-15T07:21:49.244+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-15T07:21:49.278+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
