[2025-04-15T07:29:24.854+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Anas.send_dataframe_to_kafka_task manual__2025-04-15T07:29:18.381920+00:00 [queued]>
[2025-04-15T07:29:24.866+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Anas.send_dataframe_to_kafka_task manual__2025-04-15T07:29:18.381920+00:00 [queued]>
[2025-04-15T07:29:24.866+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-15T07:29:24.866+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-04-15T07:29:24.866+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-15T07:29:24.882+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): send_dataframe_to_kafka_task> on 2025-04-15 07:29:18.381920+00:00
[2025-04-15T07:29:24.894+0000] {standard_task_runner.py:55} INFO - Started process 405 to run task
[2025-04-15T07:29:24.899+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Anas', 'send_dataframe_to_kafka_task', 'manual__2025-04-15T07:29:18.381920+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/day.py', '--cfg-path', '/tmp/tmphyxkno1s']
[2025-04-15T07:29:24.902+0000] {standard_task_runner.py:83} INFO - Job 80: Subtask send_dataframe_to_kafka_task
[2025-04-15T07:29:24.981+0000] {task_command.py:388} INFO - Running <TaskInstance: Anas.send_dataframe_to_kafka_task manual__2025-04-15T07:29:18.381920+00:00 [running]> on host 0c4d66587ca1
[2025-04-15T07:29:25.075+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Anas
AIRFLOW_CTX_TASK_ID=send_dataframe_to_kafka_task
AIRFLOW_CTX_EXECUTION_DATE=2025-04-15T07:29:18.381920+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-15T07:29:18.381920+00:00
[2025-04-15T07:29:25.079+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.20.0.6', 9092)]>: connecting to kafka:9092 [('172.20.0.6', 9092) IPv4]
[2025-04-15T07:29:25.084+0000] {conn.py:615} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.20.0.6', 9092)]>: Broker version identified as 2.6
[2025-04-15T07:29:25.084+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.20.0.6', 9092)]>: Connection complete.
[2025-04-15T07:29:25.190+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.20.0.6', 9092)]>: connecting to kafka:9092 [('172.20.0.6', 9092) IPv4]
[2025-04-15T07:29:25.190+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.20.0.6', 9092)]>: Connection complete.
[2025-04-15T07:29:25.191+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.20.0.6', 9092)]>: Closing connection. 
[2025-04-15T07:29:25.198+0000] {logging_mixin.py:137} INFO - Success!
[2025-04-15T07:29:25.214+0000] {logging_mixin.py:137} INFO - Error sending records to Kafka: 'str' object has no attribute 'to_dict'
[2025-04-15T07:29:25.214+0000] {kafka.py:511} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2025-04-15T07:29:25.216+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.20.0.6', 9092)]>: Closing connection. 
[2025-04-15T07:29:25.216+0000] {logging_mixin.py:137} INFO - Kafka producer closed.
[2025-04-15T07:29:25.217+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/day.py", line 31, in send_df_to_kafka
    df=df.to_dict(orient='records')
AttributeError: 'str' object has no attribute 'to_dict'
[2025-04-15T07:29:25.229+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Anas, task_id=send_dataframe_to_kafka_task, execution_date=20250415T072918, start_date=20250415T072924, end_date=20250415T072925
[2025-04-15T07:29:25.250+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 80 for task send_dataframe_to_kafka_task ('str' object has no attribute 'to_dict'; 405)
[2025-04-15T07:29:25.271+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-15T07:29:25.308+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
